# Generated by Django 5.0.14 on 2026-03-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=100, verbose_name='Nome do Solicitante')),
                ('nome_peca', models.CharField(max_length=150, verbose_name='PN ou Nome da Peça')),
                ('prazo', models.DateField(verbose_name='Prazo para Execução')),
                ('prioridade', models.CharField(choices=[('B', 'Baixa'), ('N', 'Normal'), ('A', 'Alta'), ('U', 'Urgente')], default='N', max_length=1, verbose_name='Prioridade')),
                ('status', models.CharField(choices=[('F', 'Na Fila'), ('I', 'Imprimindo'), ('C', 'Concluído'), ('E', 'Cancelado/Erro')], default='F', max_length=1, verbose_name='Status Atual')),
                ('arquivo_impressao', models.FileField(blank=True, null=True, upload_to='arquivos_3d/', verbose_name='Arquivo (STL/GCODE)')),
                ('link_fusion', models.URLField(blank=True, null=True, verbose_name='Link do Fusion 360')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Solicitação')),
            ],
        ),
    ]
