# Generated by Django 5.0.14 on 2026-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfila',
            name='status',
            field=models.CharField(choices=[('F', 'Na Fila'), ('I', 'Imprimindo'), ('P', 'Pendente de Informação'), ('C', 'Concluído'), ('E', 'Cancelado/Erro')], default='F', max_length=1, verbose_name='Status Atual'),
        ),
    ]
