# Generated by Django 5.0.14 on 2026-03-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0002_alter_itemfila_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfila',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora de Conclusão'),
        ),
    ]
