# Generated by Django 5.0.14 on 2026-03-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fila", "0003_itemfila_data_conclusao"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido3D",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "solicitante",
                    models.CharField(
                        max_length=100, verbose_name="Nome do Solicitante"
                    ),
                ),
                (
                    "nome_peca",
                    models.CharField(max_length=150, verbose_name="PN ou Nome da Peça"),
                ),
                ("prazo", models.DateField(verbose_name="Prazo para Execução")),
                (
                    "previsao_conclusao",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Previsão de Conclusão (Gestor)",
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("B", "Baixa"),
                            ("N", "Normal"),
                            ("A", "Alta"),
                            ("U", "Urgente"),
                        ],
                        default="N",
                        max_length=1,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("F", "Na Fila"),
                            ("I", "Em Produção"),
                            ("P", "Pendente de Informação"),
                            ("C", "Concluído"),
                            ("E", "Cancelado/Erro"),
                        ],
                        default="F",
                        max_length=1,
                        verbose_name="Status Atual",
                    ),
                ),
                (
                    "arquivo_impressao",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="arquivos_3d/",
                        verbose_name="Arquivo (STL/GCODE)",
                    ),
                ),
                (
                    "link_fusion",
                    models.URLField(
                        blank=True, null=True, verbose_name="Link do Fusion 360"
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Solicitação"
                    ),
                ),
                (
                    "data_conclusao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data/Hora de Conclusão"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PedidoCAD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "solicitante",
                    models.CharField(
                        max_length=100, verbose_name="Nome do Solicitante"
                    ),
                ),
                (
                    "nome_peca",
                    models.CharField(
                        max_length=150, verbose_name="PN ou Nome do Projeto"
                    ),
                ),
                ("prazo", models.DateField(verbose_name="Prazo para Execução")),
                (
                    "previsao_conclusao",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Previsão de Conclusão (Gestor)",
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("B", "Baixa"),
                            ("N", "Normal"),
                            ("A", "Alta"),
                            ("U", "Urgente"),
                        ],
                        default="N",
                        max_length=1,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("F", "Na Fila"),
                            ("I", "Em Produção"),
                            ("P", "Pendente de Informação"),
                            ("C", "Concluído"),
                            ("E", "Cancelado/Erro"),
                        ],
                        default="F",
                        max_length=1,
                        verbose_name="Status Atual",
                    ),
                ),
                (
                    "arquivo_impressao",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="arquivos_cad/",
                        verbose_name="Arquivo de Referência (PDF/Imagem)",
                    ),
                ),
                (
                    "link_fusion",
                    models.URLField(
                        blank=True, null=True, verbose_name="Link de Referência"
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Solicitação"
                    ),
                ),
                (
                    "data_conclusao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data/Hora de Conclusão"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PedidoRouter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "solicitante",
                    models.CharField(
                        max_length=100, verbose_name="Nome do Solicitante"
                    ),
                ),
                (
                    "nome_peca",
                    models.CharField(max_length=150, verbose_name="PN ou Nome da Peça"),
                ),
                ("prazo", models.DateField(verbose_name="Prazo para Execução")),
                (
                    "previsao_conclusao",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Previsão de Conclusão (Gestor)",
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("B", "Baixa"),
                            ("N", "Normal"),
                            ("A", "Alta"),
                            ("U", "Urgente"),
                        ],
                        default="N",
                        max_length=1,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("F", "Na Fila"),
                            ("I", "Em Produção"),
                            ("P", "Pendente de Informação"),
                            ("C", "Concluído"),
                            ("E", "Cancelado/Erro"),
                        ],
                        default="F",
                        max_length=1,
                        verbose_name="Status Atual",
                    ),
                ),
                (
                    "arquivo_impressao",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="arquivos_router/",
                        verbose_name="Arquivo (DXF/Vectric)",
                    ),
                ),
                (
                    "link_fusion",
                    models.URLField(
                        blank=True, null=True, verbose_name="Link do Projeto"
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Solicitação"
                    ),
                ),
                (
                    "data_conclusao",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data/Hora de Conclusão"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ItemFila",
        ),
    ]
