# Generated by Django 5.0.14 on 2026-03-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0003_itemfila_data_conclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfila',
            name='previsao_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Previsão de Conclusão (Gestor)'),
        ),
    ]
