# Generated by Django 5.0.14 on 2026-03-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fila', '0005_pedido3d_pedidocad_pedidorouter_delete_itemfila'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido3d',
            name='observacao_pendencia',
            field=models.TextField(blank=True, null=True, verbose_name='Observação de Pendência'),
        ),
        migrations.AddField(
            model_name='pedidocad',
            name='observacao_pendencia',
            field=models.TextField(blank=True, null=True, verbose_name='Observação de Pendência'),
        ),
        migrations.AddField(
            model_name='pedidorouter',
            name='observacao_pendencia',
            field=models.TextField(blank=True, null=True, verbose_name='Observação de Pendência'),
        ),
        migrations.AlterField(
            model_name='pedido3d',
            name='status',
            field=models.CharField(choices=[('D', 'Em Desenvolvimento'), ('F', 'Pronto para Iniciar'), ('I', 'Em Produção'), ('P', 'Pendente de Informação'), ('C', 'Concluído'), ('E', 'Cancelado/Erro')], default='D', max_length=1, verbose_name='Status Atual'),
        ),
        migrations.AlterField(
            model_name='pedidocad',
            name='status',
            field=models.CharField(choices=[('D', 'Em Desenvolvimento'), ('F', 'Pronto para Iniciar'), ('I', 'Em Produção'), ('P', 'Pendente de Informação'), ('C', 'Concluído'), ('E', 'Cancelado/Erro')], default='D', max_length=1, verbose_name='Status Atual'),
        ),
        migrations.AlterField(
            model_name='pedidorouter',
            name='status',
            field=models.CharField(choices=[('D', 'Em Desenvolvimento'), ('F', 'Pronto para Iniciar'), ('I', 'Em Produção'), ('P', 'Pendente de Informação'), ('C', 'Concluído'), ('E', 'Cancelado/Erro')], default='D', max_length=1, verbose_name='Status Atual'),
        ),
    ]
