upstream django_app {
    server web:8000;
}

server {
    listen 80;
    server_name _;

    client_max_body_size 100M;

    # 1. O Nginx entrega os arquivos estáticos super rápido (sem incomodar o Django)
    location /static/ {
        alias /app/static/;
    }

    # 2. O Nginx entrega os arquivos de upload (PDFs, imagens 3D)
    location /media/ {
        alias /app/media/;
    }

    # 3. A NOSSA ÁREA ULTRA SECRETA (Proteção por IP)
    location /portal-gestor-aero-2026/ {
        # DESCOMENTE AS LINHAS ABAIXO QUANDO SOUBER O SEU IP EXATO!
        # allow SEU.IP.AQUI.123; # Libera o IP do seu laboratório/empresa
        # deny all;              # Bloqueia qualquer outra pessoa no universo

        proxy_pass http://django_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # 4. O resto do Hub de Manufatura (Tráfego Normal)
    location / {
        proxy_pass http://django_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}